# Test if Rakudo builds, on each GitHub Windows runner
name: Build on GitHub Windows runners
on:
  workflow_dispatch:
env:
  VSCMD_DEBUG: 3
  VERSION: 2024.08
  REVISION: 01
  RELEASE_URL: https://rakudo.org/dl/rakudo/rakudo-${{ env.VERSION }}.tar.gz
jobs:
  build_Rakudo_Windows_Releases:
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        os: [windows-2019, windows-2022]
        sdk: [10.0.17763.0, 10.0.19041.0, 10.0.20348.0, 10.0.22000.0, 10.0.22621.0]
        #exclude:
        #  - os: windows-2022
        #    sdk: 10.0.40219
        #  - os: windows-2022
        #    sdk: 14.29.30153
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      #- name: Show vsdevcmd.trace.txt
      #  run: |
      #    vsdevcmd.bat > vsdevcmd.trace.txt 2>&1
      #    cat vsdevcmd.trace.txt
      - name: Setup VS C++ Environment
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
          sdk: ${{ matrix.sdk }}
      - name: Run the build-with-choco.ps1 script
        run: pwsh -command ".\tools\build\binary-release\build-windows.ps1"
      - name: List my stuff
        run: Get-ChildItem -Exclude ".git" -Recurse
