# Test if Rakudo builds, on each GitHub Windows runner
name: Build on GitHub Windows runners
on:
  workflow_dispatch:
env:
  VSCMD_DEBUG: 3
  VERSION: 2024.12
  REVISION: 01
  RELEASE_URL: https://rakudo.org/dl/rakudo/rakudo-2024.12.tar.gz
jobs:
  build:
    strategy:
      fail-fast: false
      # max-parallel: 7 # run 7 of 14 jobs in parallel
      matrix:
        os: [windows-2019, windows-2022]
        # see https://github.com/actions/runner-images/blob/main/images/windows/Windows2019-Readme.md#installed-windows-sdks and
        #     https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md#installed-windows-sdks
        sdk: [10.0.14393.0, 10.0.16299.0, 10.0.17134.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0, 10.0.20348.0, 10.0.22000.0, 10.0.22621.0]
        # exclude the SDKs, which are not available for 2022
        exclude:
          - os: windows-2022
            sdk: 10.0.14393.0
          - os: windows-2022
            sdk: 10.0.16299.0
          - os: windows-2022
            sdk: 10.0.16299.0
          - os: windows-2022
            sdk: 10.0.17134.0
          - os: windows-2022
            sdk: 10.0.18362.0  
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup VS SDK ${{ matrix.sdk }} on ${{ matrix.os }}
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
          sdk: ${{ matrix.sdk }}
      - name: Show CL version info
        run: |
          cl /? | Select-String "Compiler Version " -CaseSensitive
      - name: Run the build-windows.ps1 script
        run: pwsh -command ".\tools\build\binary-release\build-windows.ps1"
      - name: List my stuff
        run: Get-ChildItem -Exclude ".git" -Recurse
